

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: jdbc:h2:mem:spacecraft
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      mode: always
      continue-on-error: true
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: spacecraftservice
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  data:
    jpa:
      repositories:
        bootstrap-mode: default
