

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: jdbc:h2:mem:spacecraft
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      mode: never
      continue-on-error: true
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: spacecraftservice
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    #defer-datasource-initialization: true
  security:
    user:
      name: Jaime
      password: "2030201811*"
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0


  data:
    jpa:
      repositories:
        bootstrap-mode: default
springdoc:
  swagger-ui:
    operations-sorter: method
